passwd:
    users:
        - name: core
          ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCc9oMKbmL1Jk8W2HoFRPNal4q4Mobr8t+Knlqj3Y6ZA7UuHHGRanDAlBCSFlgJVpQ6/3YlmQyTRduWwxMymHZt0j/E0D153vOEV4rMnw/dOeeVH41qftp4VhihlXU6DxOmWdN5RdMQUPKT1CzZzZa976rYCyvgdO2p0SPvbfk3JNTsI6WEhoivWqa1HuZOUB2F2Y4U2AcsSB49JJq+hWiSioeEBt6luqd+3E8iQ2ZlvVrp9hrPSZ6D7xB5vxjYFSTm/wS8WFCw8t9uMp48RDjr4lTqzNMhx6o53Rmsd0J2bk/Wf4Q5LTVjUL5v8ej2uFaRdew6HnhuX7I6wEfQoWWf

networkd:
    units:
        - name: 00-ens192.network
          contents: |
              [Match]
              Name=ens192

              [Network]
              Address=10.1.0.10/24
        - name: 01-ens224.network
          contents: |
              [Match]
              Name=ens224

              [Network]
              DHCP=yes

systemd:
    units:
        - name: docker.service
          enable: true
          dropins:
              - name: 40-flannel.conf
                contents: |
                    [Unit]
                    Requires=flanneld.service
                    After=flanneld.service
                    [Service]
                    Environment=DOCKER_OPT_BIP=""
                    Environment=DOCKER_OPT_IPMASQ=""

        - name: kubelet.service
          enable: true
          contents: |
              [Service]
              Environment=KUBELET_IMAGE_TAG=v1.10.4_coreos.0
              Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
                --volume var-log,kind=host,source=/var/log \
                --mount volume=var-log,target=/var/log \
                --volume dns,kind=host,source=/etc/resolv.conf \
                --mount volume=dns,target=/etc/resolv.conf"
              ExecStartPre=/usr/bin/mkdir -p /var/log/containers
              ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/run/kubelet-pod.uuid
              ExecStart=/usr/lib/coreos/kubelet-wrapper \
                  --kubeconfig=/etc/kubernetes/kubeconfig.yaml \
                  --config=/etc/kubernetes/kubeletconfig.yaml \
                  --cni-conf-dir=/etc/kubernetes/cni/net.d \
                  --container-runtime=docker \
                  --register-node=true \
                  --hostname-override=cluster1-worker1
              ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
              Restart=always
              RestartSec=10
              
              [Install]
              WantedBy=multi-user.target


storage:
    disks:
        - device: /dev/sda
          wipe_table: true
          partitions:
              - label: ROOT
    filesystems:
        - mount:
            device: /dev/disk/by-partlabel/ROOT
            format: ext4
            wipe_filesystem: true
            label: ROOT
    files:
        - filesystem: root
          path: /etc/hostname
          mode: 420
          contents:
              inline: cluster1-worker1
        - filesystem: root
          path: /etc/hosts
          append: true
          mode: 420
          contents: 
              inline: |
                  10.1.0.1  cluster1-master
        - filesystem: root
          path: /etc/kubernetes/cni/net.d/10-flannel.conf
          mode: 420
          contents:
              inline: |
                  {
                      "name": "podnet",
                      "type": "flannel",
                      "delegate": {
                          "isDefaultGateway": true
                      }
                  }
        - filesystem: root
          path: /etc/kubernetes/kubeconfig.yaml
          mode: 420
          contents:
              local: kubeconfig.yaml
        - filesystem: root
          path: /etc/kubernetes/kubeletconfig.yaml
          mode: 420
          contents:
              local: kubeletconfig.yaml
        - filesystem: root
          path: /etc/kubernetes/ssl/worker.pem
          mode: 384
          contents:
              local: ssl/kube-1-worker.pem
        - filesystem: root
          path: /etc/kubernetes/ssl/worker-key.pem
          mode: 384
          contents:
              local: ssl/kube-1-worker-key.pem
        - filesystem: root
          path: /etc/kubernetes/ssl/ca.pem
          mode: 384
          contents:
              local: ssl/ca.pem
        - filesystem: root
          path: /etc/kubernetes/manifests/kube-proxy.yaml
          mode: 420
          contents:
              local: kube-proxy.yaml

flannel:
    network_config: '{"Network": "10.5.0.0/24"}'
    etcd_endpoints: http://cluster1-master:2379
    #etcd_prefix: /cluster1.kcz.sh/network
    interface: ens192

