apiVersion: v1
kind: Config
preferences: {}
clusters:
    - cluster:
        api-version: v1
        server: https://cluster1-master
        name: cluster1
        certificate-authority: /etc/kubernetes/ssl/ca.pem
users:
    - name: kubelet
      user:
          client-certificate: /etc/kubernetes/ssl/worker.pem
          client-key: /etc/kubernetes/ssl/worker-key.pem
contexts:
    - context:
        cluster: cluster1
        user: kubelet
      name: context1
current-context: context1
