apiVersion: v1
kind: Config
preferences: {}
clusters:
    - name: cluster1
      cluster:
        api-version: v1
        server: https://192.168.1.101
        certificate-authority: ssl/ca.pem
users:
    - name: cookies
      user:
          client-certificate: ssl/client-cookies.pem
          client-key: ssl/client-cookies-key.pem
    - name: admin
      user:
          client-certificate: ssl/admin.pem
          client-key: ssl/admin-key.pem
contexts:
    - name: context1
      context:
        cluster: cluster1
        user: cookies
    - name: admin
      context:
        cluster: cluster1
        user: admin
current-context: context1
