kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cookies-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cookies-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cookies-admin
subjects:
- kind: User
  name: cookies
